vich_uploader:
    db_driver: orm

    mappings:
        tips_image:
            uri_prefix: /images/tips
            upload_destination: '%kernel.project_dir%/public/assets/images/tips'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#
#        user_image:
#            uri_prefix: /images/users
#            upload_destination: '%kernel.project_dir%/public/assets/images/users'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
